"""HTML report rendering. Self-contained, theme-aware, no external assets."""

from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path

SEV_LABEL = {"critical": "Critical", "high": "High", "medium": "Medium", "low": "Low"}

CSS = """
:root{
  --bg:#f7f7f5; --surface:#fff; --border:#e3e2de; --text:#1a1a18;
  --muted:#6b6a66; --dim:#93918b;
  --critical:#b3261e; --high:#b5651d; --medium:#8a7420; --low:#5b6b7a;
  --ok:#2f6f4f; --accent:#1a1a18;
  --shadow:0 1px 2px rgba(0,0,0,.05),0 1px 8px rgba(0,0,0,.03);
}
@media (prefers-color-scheme:dark){
  :root:not([data-theme="light"]){
    --bg:#16171a; --surface:#1e2024; --border:#2e3138; --text:#e9e8e4;
    --muted:#a2a09a; --dim:#75736e;
    --critical:#ef6a60; --high:#e0954a; --medium:#d3bb55; --low:#8fa6bb;
    --ok:#6cc294; --accent:#e9e8e4;
    --shadow:0 1px 2px rgba(0,0,0,.3),0 1px 8px rgba(0,0,0,.2);
  }
}
:root[data-theme="dark"]{
  --bg:#16171a; --surface:#1e2024; --border:#2e3138; --text:#e9e8e4;
  --muted:#a2a09a; --dim:#75736e;
  --critical:#ef6a60; --high:#e0954a; --medium:#d3bb55; --low:#8fa6bb;
  --ok:#6cc294; --accent:#e9e8e4;
  --shadow:0 1px 2px rgba(0,0,0,.3),0 1px 8px rgba(0,0,0,.2);
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);
  font:15px/1.55 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  -webkit-font-smoothing:antialiased}
.wrap{max-width:960px;margin:0 auto;padding:48px 24px 96px}
header{margin-bottom:40px}
h1{font-size:30px;letter-spacing:-.02em;margin:0 0 6px;font-weight:650}
.sub{color:var(--muted);font-size:14px}
.totals{display:flex;flex-wrap:wrap;gap:10px;margin:28px 0 8px}
.stat{background:var(--surface);border:1px solid var(--border);border-radius:10px;
  padding:12px 16px;min-width:104px;box-shadow:var(--shadow)}
.stat .n{font-size:24px;font-weight:640;letter-spacing:-.02em;
  font-variant-numeric:tabular-nums;line-height:1.15}
.stat .l{font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:var(--dim);margin-top:3px}
.n.critical{color:var(--critical)} .n.high{color:var(--high)}
.n.medium{color:var(--medium)} .n.low{color:var(--low)} .n.ok{color:var(--ok)}
.repo{background:var(--surface);border:1px solid var(--border);border-radius:12px;
  margin-bottom:14px;overflow:hidden;box-shadow:var(--shadow)}
.repo>summary{cursor:pointer;padding:15px 18px;display:flex;align-items:center;
  gap:12px;list-style:none;user-select:none}
.repo>summary::-webkit-details-marker{display:none}
.repo>summary::before{content:"›";color:var(--dim);font-size:17px;
  transition:transform .15s ease;display:inline-block;width:9px}
.repo[open]>summary::before{transform:rotate(90deg)}
.rname{font-weight:600;letter-spacing:-.01em}
.rmeta{color:var(--dim);font-size:12.5px;margin-left:auto;
  font-variant-numeric:tabular-nums;text-align:right}
.pill{font-size:10.5px;text-transform:uppercase;letter-spacing:.06em;
  padding:2.5px 8px;border-radius:99px;border:1px solid currentColor;font-weight:600}
.pill.critical{color:var(--critical)} .pill.high{color:var(--high)}
.pill.medium{color:var(--medium)} .pill.low{color:var(--low)} .pill.ok{color:var(--ok)}
.findings{border-top:1px solid var(--border);padding:4px 18px 14px}
.f{padding:15px 0;border-bottom:1px dashed var(--border)}
.f:last-child{border-bottom:0}
.ftitle{font-weight:600;display:flex;align-items:center;gap:9px;margin-bottom:5px}
.fdetail{color:var(--muted);font-size:14px}
.paths{margin:9px 0 0;padding:9px 11px;background:var(--bg);border-radius:7px;
  border:1px solid var(--border);font:12px/1.65 ui-monospace,SFMono-Regular,Menlo,monospace;
  color:var(--muted);overflow-x:auto;white-space:pre}
.fix{margin-top:9px;font-size:13.5px;color:var(--muted);
  padding-left:11px;border-left:2px solid var(--border)}
.fix b{color:var(--text);font-weight:600}
.clean{padding:15px 18px;color:var(--ok);font-size:14px}
footer{margin-top:40px;color:var(--dim);font-size:12.5px;text-align:center}
@media (max-width:600px){
  .wrap{padding:32px 16px 64px} h1{font-size:24px}
  .rmeta{margin-left:0;width:100%;text-align:left;margin-top:3px}
  .repo>summary{flex-wrap:wrap}
}
"""


def render(repos, root: str) -> str:
    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for r in repos:
        for f in r.findings:
            if f.severity in counts:
                counts[f.severity] += 1
    clean = sum(1 for r in repos if not r.findings)

    parts = [
        "<!-- generated by gitsweep -->",
        f"<title>Repo Audit</title><style>{CSS}</style>",
        '<div class="wrap"><header>',
        "<h1>Repo Audit</h1>",
        f'<div class="sub">{len(repos)} repositories under '
        f"<code>{html.escape(root)}</code> · "
        f'{datetime.now().strftime("%Y-%m-%d %H:%M")}</div>',
        '<div class="totals">',
        f'<div class="stat"><div class="n critical">{counts["critical"]}</div>'
        '<div class="l">Critical</div></div>',
        f'<div class="stat"><div class="n high">{counts["high"]}</div>'
        '<div class="l">High</div></div>',
        f'<div class="stat"><div class="n medium">{counts["medium"]}</div>'
        '<div class="l">Medium</div></div>',
        f'<div class="stat"><div class="n low">{counts["low"]}</div>'
        '<div class="l">Low</div></div>',
        f'<div class="stat"><div class="n ok">{clean}</div>'
        '<div class="l">Clean</div></div>',
        "</div></header>",
    ]

    for r in repos:
        worst = r.findings[0].severity if r.findings else "ok"
        openattr = " open" if worst in ("critical", "high") else ""
        label = SEV_LABEL.get(worst, "Clean")
        parts.append(f'<details class="repo"{openattr}><summary>')
        parts.append(f'<span class="pill {worst}">{label}</span>')
        parts.append(f'<span class="rname">{html.escape(r.name)}</span>')
        meta = f"{len(r.findings)} finding{'s' if len(r.findings) != 1 else ''} · score {r.score}"
        parts.append(f'<span class="rmeta">{meta}</span></summary>')

        if not r.findings:
            parts.append('<div class="clean">Nothing flagged.</div></details>')
            continue

        parts.append('<div class="findings">')
        for f in r.findings:
            parts.append('<div class="f">')
            parts.append(
                f'<div class="ftitle"><span class="pill {f.severity}">'
                f"{SEV_LABEL[f.severity]}</span>{html.escape(f.title)}</div>"
            )
            parts.append(f'<div class="fdetail">{html.escape(f.detail)}</div>')
            if f.paths:
                parts.append(
                    '<div class="paths">' + html.escape("\n".join(f.paths)) + "</div>"
                )
            if f.fix:
                parts.append(f'<div class="fix"><b>Fix:</b> {html.escape(f.fix)}</div>')
            parts.append("</div>")
        parts.append("</div></details>")

    parts.append(
        '<footer>gitsweep · findings are heuristics, not proof — '
        "read before acting</footer></div>"
    )
    return "\n".join(parts)


def write(repos, root: str, dest: Path) -> Path:
    dest.write_text(render(repos, root), encoding="utf-8")
    return dest
